app:
  properties:
    publisher-rate-millis: ${PUBLISHER_RATE_MILLIS:3000}
    bus-location-source-file: ${BUS_LOCATION_SOURCE_FILE:src/main/resources/busPositions.txt}
    kafka-default-topic: ${KAFKA_DEFAULT_TOPIC:bus.locations}

spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: bus.updates
      bootstrap-servers: localhost:29092
      max-poll-records: 1
      auto-offset-reset: earliest
    producer:
      bootstrap-servers: localhost:29092
